### ISSUE TITLE
Cannot Chat with Myshkin @Nikola_bot

### ISSUE THREAD

**Issue by 4poorv** [suriyadeepan/myshkin#1]
I connected with Myshkin @Nikola_bot through telegram.
Found a weird bot name and broken link which looks like a spam.
![telegram_001](https://cloud.githubusercontent.com/assets/13313876/23254784/4419b972-f9df-11e6-83a4-e5f410b15de7.png)

**Comment by suriyadeepan** [comment]
yeah.. that's not my bot! i've stopped it last year!
